In [1]:
import numpy as np
import cv2

In [2]:
img=cv2.imread("./data/faces.jpg")

cv2.imshow("faces",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
face_detection_model=cv2.dnn.readNetFromCaffe('./data/DNN FD/models/deploy.prototxt.txt',
                                              './data/DNN FD/models/res10_300x300_ssd_iter_140000_fp16.caffemodel')

In [4]:

# step 1: blob from image
blob=cv2.dnn.blobFromImage(img,1,(300,300),(104,177,123),swapRB=True)
        
#step 2 set blob as imput
face_detection_model.setInput(blob)
        
# step 3 output
detections=face_detection_model.forward()
        
#step 4 drawing bounding box on top of detected face
image=img.copy()
h,w=image.shape[:2]
for i in range(0,detections.shape[2]):
    confidence=detections[0,0,i,2]
    if(confidence>0.5):
        #print(confidence)
        #diagonal points 3:7
        box=detections[0,0,i,3:7]*np.array([w,h,w,h]) # denormalizing the width cause the cordinates given is with respect to width
        box=box.astype('int')
        print(box)
        pt1=(box[0],box[1])
        pt2=(box[2],box[3])
        #drawing rectangle
        cv2.rectangle(image,pt1,pt2,(0,255,0),1)
        
        text="score:{:.0f} %".format(confidence*100)
        cv2.putText(image,text,pt1,cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2)
        
    
cv2.imshow("faces",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[138  94 362 445]
[406 121 641 472]
[729 102 924 375]


In [5]:
detections

array([[[[0.        , 1.        , 0.99828076, ..., 0.13435304,
          0.37747657, 0.6368804 ],
         [0.        , 1.        , 0.93064046, ..., 0.1735116 ,
          0.66801995, 0.6749054 ],
         [0.        , 1.        , 0.6649139 , ..., 0.14685199,
          0.96339893, 0.53605294],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]]]], dtype=float32)

In [6]:
detections.shape

(1, 1, 200, 7)

In [7]:
detections[0,0,:,2]

array([0.99828076, 0.93064046, 0.6649139 , 0.11303055, 0.0990653 ,
       0.09581406, 0.0953909 , 0.09210995, 0.09148149, 0.0900412 ,
       0.0895226 , 0.08925451, 0.08845702, 0.0883582 , 0.08817663,
       0.0878502 , 0.08761991, 0.08759254, 0.08733164, 0.086446  ,
       0.08633808, 0.08580604, 0.08571839, 0.08569968, 0.08565523,
       0.08561652, 0.08543263, 0.08516434, 0.08498954, 0.08490543,
       0.08472107, 0.08466659, 0.08451294, 0.08432198, 0.08402867,
       0.08339364, 0.08325935, 0.08319437, 0.08300184, 0.08287058,
       0.08281695, 0.0828022 , 0.08230655, 0.0820657 , 0.08128534,
       0.08119455, 0.08109774, 0.0810788 , 0.08065075, 0.08063321,
       0.08060356, 0.08035444, 0.08024477, 0.07988586, 0.07988258,
       0.0797419 , 0.07961009, 0.07956649, 0.07941596, 0.07937436,
       0.07934451, 0.0792764 , 0.07913708, 0.07913007, 0.0790798 ,
       0.07904799, 0.07900919, 0.07894585, 0.07892095, 0.07890498,
       0.0788851 , 0.07886865, 0.07882137, 0.07861339, 0.07850

In [8]:
def fd_dnn(img):
        # step 1: blob from image
        blob=cv2.dnn.blobFromImage(img,1,(300,300),(104,177,123),swapRB=True)
        
        #step 2 set blob as imput
        face_detection_model.setInput(blob)
        
        # step 3 output
        detections=face_detection_model.forward()
        
        #step 4 drawing bounding box on top of detected face
        image=img.copy()
        h,w=image.shape[:2]
        for i in range(0,detections.shape[2]):
            confidence=detections[0,0,i,2]
            if(confidence>0.5):
                #print(confidence)
                #diagonal points 3:7
                box=detections[0,0,i,3:7]*np.array([w,h,w,h]) # denormalizing the width cause the cordinates given is with respect to width
                box=box.astype('int')
                print(box)
                pt1=(box[0],box[1])
                pt2=(box[2],box[3])
                #drawing rectangle
                cv2.rectangle(image,pt1,pt2,(0,255,0),1)
        
                text="score:{:.0f} %".format(confidence*100)
                cv2.putText(image,text,pt1,cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),2)
        return image

In [9]:
img_detect=fd_dnn(img)

[138  94 362 445]
[406 121 641 472]
[729 102 924 375]


In [10]:
cv2.imshow("face detection",img_detect)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
# real time face detection

In [13]:
cap=cv2.VideoCapture(0)
face_detection_model=cv2.dnn.readNetFromCaffe('./data/DNN FD/models/deploy.prototxt.txt',
                                              './data/DNN FD/models/res10_300x300_ssd_iter_140000_fp16.caffemodel')

while True:
    ret,frame=cap.read()
    if ret == False:
        break

    img_detection=fd_dnn(frame)
    cv2.imshow("face detection",img_detection)
    if cv2.waitKey(1)==ord('d'):
        break
        
cap.release()
cv2.destroyAllWindows()


[342 183 500 385]
[342 183 501 386]
[342 183 501 386]
[341 183 500 387]
[341 183 500 387]
[340 183 501 386]
[341 184 501 388]
[341 184 501 388]
[342 184 499 388]
[342 184 499 388]
[342 185 501 387]
[342 185 501 387]
[342 182 502 388]
[340 183 501 388]
[340 183 501 388]
[338 186 500 389]
[338 186 500 392]
[338 186 500 392]
[337 186 500 392]
[337 186 500 392]
[342 187 504 395]
[344 192 503 396]
[344 192 503 396]
[344 194 504 396]
[344 194 504 396]
[343 197 502 398]
[343 196 501 399]
[343 196 501 399]
[341 198 502 400]
[341 198 502 400]
[342 200 501 401]
[342 199 502 400]
[342 199 502 400]
[343 200 502 403]
[343 200 502 403]
[343 200 501 402]
[343 201 500 403]
[343 201 500 403]
[343 200 501 403]
[343 200 501 403]
[343 200 500 403]
[342 199 501 405]
[342 199 501 405]
[342 200 501 402]
[342 200 501 402]
[343 200 501 405]
[343 199 502 404]
[343 199 502 404]
[343 198 503 403]
[343 198 503 403]
[343 201 501 405]
[342 201 500 406]
[342 201 500 406]
[343 201 500 405]
[343 201 500 405]
[342 202 5